language: python

cache:
  directories:
    - gecko

env:
  - DISPLAY=':99.0'

addons:
  apt:
    packages:
      - autoconf2.13

install:
  - pip install --upgrade pip
  - pip install -U mercurial
  - ./clone-gecko.sh

before_script:
  - ./build-firefox.sh
  - sh -e /etc/init.d/xvfb start

script:
  - ./build-devtools-xpi.sh
  - cd gecko
  - ls -l $PWD/../devtools.xpi
  - ./mach mochitest devtools/ --install-extension $PWD/../devtools.xpi 2>&1 | tee mochitest-logs | grep -E "TEST-(START|OK|UNEXPECTED)"
  - cd ..
