cache:
  directories:
    - gecko

install:
  - ! [ -d gecko ] && git clone --depth 1 https://github.com/mozilla/gecko-dev.git gecko
  - cd gecko
  - git fetch
  - git checkout 

before_script:
  - cd gecko
  - echo "ac_add_options --enable-artifact-builds" > mozconfig
  - echo "mk_add_options AUTOCLOBBER=1 >> mozconfig
  - ./mach build

script:
  - cd gecko
  - ./mach mochitest devtools/ --install-addon ../devtools.xpi

